language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - composer install

before_install: echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: vendor/bin/phpunit
